# This file created by conda-build 2.1.18
# meta.yaml template originally from:
# /opt/recipe, last modified Thu Feb 15 19:47:41 2018
# ------------------------------------------------

package:
    name: vcf2maf
    version: 1.6.16
source:
    fn: v1.6.16.tar.gz
    sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
    url: https://github.com/mskcc/vcf2maf/archive/v1.6.16.tar.gz
build:
    noarch: ''
    noarch_python: false
    number: '1'
    string: pl5.22.0_1
requirements:
    build:
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - variant-effect-predictor 87 0
        - certifi 2018.1.18 py36_0
        - htslib 1.7 0
        - perl-archive-extract 0.76 3
        - python 3.6.4 0
        - mysqlclient 1.3.10 py36_0
        - xz 5.2.3 0
        - perl-dbi 1.640 pl5.22.0_0
        - openssl 1.0.2n 0
        - perl-threaded 5.22.0 pl5.22.0_12
        - perl-file-sharedir 1.102 3
        - samtools 1.7 1
        - perl-bio-db-hts 2.7 htslib1.7_1
        - pip 9.0.1 py36_1
        - readline 7.0 0
        - setuptools 38.5.1 py36_0
        - perl-file-fetch 0.48 3
        - bzip2 1.0.6 1
        - zlib 1.2.11 0
        - libgcc-ng 7.2.0 h7cc24e2_2
        - perl-file-sharedir-install 0.10 3
        - perl-compress-raw-zlib 2.069 3
        - tk 8.6.7 0
        - perl-app-cpanminus 1.7039 pl5.22.0_3
        - perl-yaml 1.18 0
        - perl-exporter-tiny 0.042 1
        - perl-cgi 4.22 3
        - perl-lwp-simple 6.15 3
        - perl-archive-zip 1.55 3
        - libssh2 1.8.0 2
        - perl-list-moreutils 0.428 pl5.22.0_0
        - perl-bioperl 1.6.924 4
        - libgcc 7.2.0 h69d50b8_2
        - krb5 1.14.2 0
        - perl-ipc-system-simple 1.25 3
        - ca-certificates 2018.1.18 0
        - mysql-connector-c 6.1.6 2
        - ncurses 5.9 10
        - perl 5.22.0.1 0
        - curl 7.55.1 0
        - wheel 0.30.0 py36_2
        - perl-encode-locale 1.05 pl5.22.0_4
        - perl-file-copy-recursive 0.38 1
        - sqlite 3.20.1 2
        - perl-lwp-protocol-https 6.06 2
        - perl-time-hires 1.9728 pl5.22.0_4
        - perl-dbd-mysql 4.033 2
        - perl-statistics-descriptive 3.0612 0
    run:
        - perl
        - variant-effect-predictor
        - samtools
        - htslib 1.7*
test:
    commands:
        - vcf2maf.pl --help
about:
    home: https://github.com/mskcc/vcf2maf
    license: Apache-2.0
    summary: Convert a VCF into a MAF where each variant is annotated to only one
        of all possible gene isoforms
extra:
    final: true
    notes: 'This package installs only vcf2maf and does not integrate with the variant-effect-predictor
        (VEP). To

        do so, please follow the instructions at https://github.com/mskcc/vcf2maf/blob/master/README.md.

        '
